from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.NUM_CLASSES = 10

_C.INPUT = CN()
_C.INPUT.SIZE_TRAIN = 32
_C.INPUT.SIZE_TEST = 32
_C.INPUT.MIN_SCALE_TRAIN = 0.5
_C.INPUT.MAX_SCALE_TRAIN = 1.2
_C.INPUT.PROB = 0.5
_C.INPUT.PIXEL_MEAN = [0.1307, ]
_C.INPUT.PIXEL_STD = [0.3081, ]

_C.DATASETS = CN()
_C.DATASETS.TRAIN = ()
_C.DATASETS.TEST = ()

_C.DATALOADER = CN()
_C.DATALOADER.NUM_WORKERS = 8

_C.SOLVER = CN()
_C.SOLVER.OPTIMIZER_NAME = "SGD"

_C.SOLVER.MAX_EPOCHS = 50

_C.SOLVER.BASE_LR = 0.001
_C.SOLVER.BIAS_LR_FACTOR = 2

_C.SOLVER.MOMENTUM = 0.9

_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.WEIGHT_DECAY_BIAS = 0

_C.SOLVER.GAMMA = 0.1
_C.SOLVER.STEPS = (30000,)

_C.SOLVER.WARMUP_FACTOR = 1.0 / 3
_C.SOLVER.WARMUP_ITERS = 500
_C.SOLVER.WARMUP_METHOD = "linear"

_C.SOLVER.CHECKPOINT_PERIOD = 10
_C.SOLVER.LOG_PERIOD = 100

_C.SOLVER.IMS_PER_BATCH = 16

_C.TEST = CN()
_C.TEST.IMS_PER_BATCH = 8
_C.TEST.WEIGHT = ""

_C.OUTPUT_DIR = ""
